(function(){
const D=window.ESG_DATA, R=window.ESG_ROUTER, app=document.getElementById('app'), back=document.getElementById('backBtn'), menuBtn=document.getElementById('menuBtn'), menu=document.getElementById('menuPopover');
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const btn=(label,attrs='',cls='btn-primary')=>`<button class="btn ${cls}" ${attrs}>${label}</button>`;
const list=arr=>`<ul class="list">${(arr||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;
const detailItems=arr=>`<div class="detail-stack">${(arr||[]).map(x=>`<article class="detail-item"><h3>${esc(x.h)}</h3><p>${esc(x.p)}</p></article>`).join('')}</div>`;
function setDocTitle(t){document.title=`${t} · ESG Experience™`}
function scrollTop(){window.scrollTo({top:0,behavior:'instant'});setTimeout(()=>app.focus({preventScroll:true}),0)}
function familyCard(f){return `<article class="stone-card family-card"><span class="eyebrow">${esc(f.eyebrow)}</span><h3>${esc(f.title)}</h3><p>${esc(f.intro)}</p><div class="price">${esc(f.price)}</div><div class="muted">${esc(f.value)}</div><div class="btn-row">${btn('Explorar','data-route="family" data-family="'+f.id+'"','btn-dark')}</div></article>`}
function renderHome(){setDocTitle('Inicio');app.innerHTML=`
<section class="hero"><div class="hero-copy"><span class="eyebrow">ESG Experience™</span><h1>${D.brand.slogan}</h1><p>${D.brand.sub}</p><div class="glass-card"><img class="butterfly-mark" src="assets/esg-butterfly.png" alt=""><strong>${D.brand.transversal.name}</strong><p class="small">${D.brand.transversal.text}</p></div><div class="btn-row">${btn('Ya sé lo que necesito','data-route="request-picker"')}</div></div><div class="hero-art"><img src="assets/elenia-portrait.png" alt="Elenia, avatar oficial de ESG Experience"></div></section>
<section class="section"><div class="section-head"><span class="eyebrow">Elige por dónde quieres comenzar</span><h2 class="section-title">Tres caminos. Una marca más clara.</h2></div><div class="grid grid-3">${Object.values(D.families).map(familyCard).join('')}</div></section>
<section class="section stone-card"><span class="eyebrow">Cómo trabajamos</span><h2>Primero entiendes. Después decides.</h2><p>No enviamos a una persona a llenar formularios sin explicar qué está comprando. Cada servicio desarrolla el problema, la transformación, lo que recibe, los límites, el precio y el checklist antes de solicitar.</p></section>
${testimonialsSection()}`}
function testimonialsSection(){return `<section class="section"><div class="section-head"><span class="eyebrow">Experiencias</span><h2 class="section-title">Testimonios</h2><p class="lead">La sección queda preparada para cargar testimonios reales desde datos, sin inventarlos.</p></div><div class="grid grid-3"><div class="glass-card testimonial-placeholder">Próximamente · testimonio real</div><div class="glass-card testimonial-placeholder">Próximamente · testimonio real</div><div class="glass-card testimonial-placeholder">Próximamente · testimonio real</div></div></section>`}
function renderFamily(family){const f=D.families[family];if(!f)return render404();setDocTitle(f.title);app.innerHTML=`<div class="breadcrumb">Inicio / ${esc(f.title)}</div><section class="hero" style="min-height:52vh"><div class="hero-copy"><span class="eyebrow">${esc(f.eyebrow)}</span><h1>${esc(f.title)}</h1><p>${esc(f.intro)}</p><div class="summary-bar"><span class="summary-pill">${esc(f.price)}</span><span class="summary-pill">${esc(f.value)}</span></div></div><div class="hero-art"><img src="assets/elenia-sheet.png" alt="Elenia"></div></section>
<section class="section grid grid-2"><article class="leather-card"><span class="eyebrow">El problema real</span><h2>${esc(f.problem)}</h2></article><article class="stone-card"><span class="eyebrow">La oportunidad</span><h2>${esc(f.transformation)}</h2></article></section>
${family==='logo'?beforeAfter():''}
<section class="section"><div class="section-head"><span class="eyebrow">Opciones</span><h2 class="section-title">Elige el nivel que corresponde a tu necesidad.</h2></div><div class="grid ${f.packages.length>1?'grid-2':''}">${f.packages.map(id=>packageCard(D.packages[id])).join('')}</div></section>`}
function beforeAfter(){return `<section class="section"><div class="section-head"><span class="eyebrow">Antes / Después</span><h2 class="section-title">La coherencia se ve antes de explicarse.</h2></div><div class="before-after"><article class="stone-card"><h3>Antes</h3><p>Contenido visualmente desconectado. Sin palabras dentro de la cuadrícula: el caos debe entenderse por color y composición.</p><div class="visual-grid chaos">${'<span></span>'.repeat(9)}</div></article><article class="stone-card"><h3>Después ESG</h3><p>Una misma identidad visual reconocible en marrón, beige y dorado. El mensaje es visual, no una clasificación de contenido.</p><div class="visual-grid coherent">${'<span></span>'.repeat(9)}</div></article></div></section>`}
function packageCard(p){return `<article class="stone-card package-card"><span class="tag">${esc(p.badge)}</span><h3>${esc(p.title)}</h3><div class="price">${esc(p.price)}</div><p>${esc(p.solves)}</p><div class="muted">${esc(p.value||'')}</div>${btn('Ver todo lo que incluye',`data-route="service" data-family="${p.family}" data-service="${Object.keys(D.packages).find(k=>D.packages[k]===p)}"`,'btn-dark')}</article>`}
function renderService(id){const p=D.packages[id];if(!p)return render404();const f=D.families[p.family];setDocTitle(p.title);app.innerHTML=`<div class="breadcrumb">Inicio / ${esc(f.title)} / ${esc(p.title)}</div><section class="glass-card"><span class="eyebrow">${esc(p.badge)}</span><h1 class="title-xl">${esc(p.title)}</h1><div class="price-hero">${esc(p.price)}</div><p class="lead">${esc(p.solves)}</p><div class="summary-bar"><span class="summary-pill">${esc(p.value||'')}</span>${p.math?`<span class="summary-pill">${esc(p.math)}</span>`:''}</div><div class="btn-row">${btn('Quiero contratar ahora',`data-route="purchase-mode" data-family="${p.family}" data-service="${id}" data-mode="now"`)}${btn('Quiero contarles primero',`data-route="purchase-mode" data-family="${p.family}" data-service="${id}" data-mode="talk"`,'btn-secondary')}</div></section>
<section class="section stone-card"><span class="eyebrow">Para quién es</span><h2>Este servicio encaja si...</h2>${list(p.forWho)}</section>
<section class="section stone-card"><span class="eyebrow">Qué recibes</span><h2>Entregables desarrollados</h2>${detailItems(p.deliverables)}</section>
${p.math?`<section class="section grid grid-2"><article class="leather-card"><span class="eyebrow">Matemática real</span><h2>${esc(p.math)}</h2></article><article class="leather-card"><span class="eyebrow">Revisiones y plazo</span><p><strong>Revisiones:</strong> ${esc(p.revisions||'Según acuerdo')}</p><p><strong>Plazo:</strong> ${esc(p.deadline||'Según acuerdo')}</p></article></section>`:''}
${p.difference?`<section class="section glass-card"><span class="eyebrow">Diferencia clave</span><h2>${esc(p.difference)}</h2></section>`:''}
${id==='logo-core'?continuity(p):''}
<section class="section stone-card"><span class="eyebrow">Checklist antes de solicitar</span><h2>Confirma que tienes claro esto.</h2>${list(p.checklist)}${p.limits?`<h3>Límites del servicio</h3>${list(p.limits)}`:''}<div class="btn-row">${btn('Estoy de acuerdo con el precio',`data-route="purchase-mode" data-family="${p.family}" data-service="${id}" data-mode="now"`)}${btn('Necesito una cotización diferente',`data-route="purchase-mode" data-family="${p.family}" data-service="${id}" data-mode="quote"`,'btn-dark')}</div></section>`}
function continuity(p){return `<section class="section"><div class="section-head"><span class="eyebrow">Continuidad exclusiva de De Logo a Personaje™</span><h2 class="section-title">Tu personaje no tiene que quedarse guardado.</h2><p class="lead">${esc(p.continuity.price)}</p></div><div class="grid grid-2">${p.continuity.modes.map(m=>`<article class="stone-card"><h3>${esc(m.h)}</h3><p>${esc(m.p)}</p></article>`).join('')}</div></section>`}
function renderRequestPicker(){setDocTitle('Comenzar solicitud');app.innerHTML=`<section class="form-card"><div class="section-head"><span class="eyebrow">Comenzar solicitud</span><h1 class="section-title">¿Qué quieres solicitar?</h1><p class="lead">Primero elige una familia. Después verás únicamente las opciones de esa familia.</p></div><div class="grid grid-3">${Object.values(D.families).map(familyCard).join('')}</div></section>`}
function renderPurchaseMode(params){const p=D.packages[params.service];if(!p)return render404();setDocTitle('Cómo quieres comenzar');app.innerHTML=`<section class="form-card"><div class="stone-card"><span class="eyebrow">${esc(p.title)} · ${esc(p.price)}</span><h1>¿Cómo quieres comenzar?</h1><div class="choice-grid"><button class="stone-card choice" data-route="client-data" data-family="${p.family}" data-service="${params.service}" data-flow="contract"><h3>Quiero contratar ahora</h3><p>Datos mínimos → modalidad de pago → acuerdo → firma → entrevista ahora o después.</p></button><button class="stone-card choice" data-route="interview-intro" data-family="${p.family}" data-service="${params.service}" data-flow="interview"><h3>Quiero contarles primero</h3><p>Mini entrevista → resumen → contrato después.</p></button></div><div class="btn-row"><a class="btn btn-secondary" target="_blank" rel="noopener" href="https://wa.me/17863032835?text=${encodeURIComponent('Quiero conversar sobre el precio de '+p.title)}">Quiero conversar sobre el precio</a><a class="btn btn-secondary" target="_blank" rel="noopener" href="https://wa.me/17863032835?text=${encodeURIComponent('Necesito una cotización diferente para '+p.title)}">Necesito una cotización diferente</a></div></div></section>`}
function renderClientData(params){const p=D.packages[params.service];setDocTitle('Datos mínimos');app.innerHTML=`<section class="stone-card form-card"><span class="eyebrow">Contratar ${esc(p.title)}</span><h1>Datos mínimos</h1><p>Solo necesitamos lo esencial para preparar el acuerdo. La entrevista puede hacerse después.</p><form id="clientForm" class="form-grid"><div class="field"><label>Nombre completo</label><input name="name" required></div><div class="field"><label>Negocio</label><input name="business" required></div><div class="field"><label>WhatsApp</label><input name="phone" required></div><div class="field"><label>Email</label><input type="email" name="email" required></div><div class="field full"><label>Modalidad de pago</label><select name="payment"><option>100% por adelantado</option><option>2 pagos</option></select></div><div class="field full">${btn('Continuar al acuerdo','type="submit"','btn-dark')}</div></form></section>`;document.getElementById('clientForm').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));sessionStorage.setItem('esgClient',JSON.stringify(data));R.navigate('agreement',{...params,payment:data.payment})}}
function agreementText(p,client){return `<p><strong>Cliente:</strong> ${esc(client.name||'')}</p><p><strong>Negocio:</strong> ${esc(client.business||'')}</p><p><strong>Servicio:</strong> ${esc(p.title)}</p><p><strong>Precio:</strong> ${esc(p.price)}</p><p><strong>Modalidad:</strong> ${esc(client.payment||'100% por adelantado')}</p><p><strong>Entregables:</strong> los descritos en la pantalla comercial del servicio seleccionado y reflejados en este acuerdo.</p><p><strong>Revisión:</strong> una ronda de correcciones razonables por entrega salvo que el paquete indique expresamente otra cantidad. No incluye rehacer un concepto completo.</p><p><strong>Dos pagos:</strong> si se elige esta modalidad, producción y entrega se dividen; la fase 2 no se entrega antes del pago de la fase 2.</p><p><strong>Servicios personalizados:</strong> los pagos dejan de ser reembolsables una vez iniciado el trabajo, salvo obligación legal o del procesador de pagos.</p><p><strong>Tarjeta:</strong> no existe checkout público. ESG enviará un Stripe Payment Link manualmente por WhatsApp.</p>`}
function renderAgreement(params){const p=D.packages[params.service],client=JSON.parse(sessionStorage.getItem('esgClient')||'{}');setDocTitle('Acuerdo ESG');app.innerHTML=`<section class="stone-card form-card"><span class="eyebrow">Acuerdo ESG</span><h1>Revisa antes de firmar</h1><div class="agreement-box">${agreementText(p,client)}</div><label class="field"><span><input id="acceptAgreement" type="checkbox"> Acepto el alcance, precio, modalidad y condiciones mostradas.</span></label><div class="signature-wrap"><canvas id="sig" width="900" height="260"></canvas></div><div class="btn-row">${btn('Limpiar firma','id="clearSig"','btn-secondary')} ${btn('Firmar y aceptar','id="signBtn"','btn-dark')}</div></section>`;setupSignature(params)}
function setupSignature(params){const c=document.getElementById('sig'),ctx=c.getContext('2d');ctx.lineWidth=3;ctx.lineCap='round';ctx.strokeStyle='#2b1a10';let down=false;const pos=e=>{const r=c.getBoundingClientRect(),p=e.touches?e.touches[0]:e;return {x:(p.clientX-r.left)*c.width/r.width,y:(p.clientY-r.top)*c.height/r.height}};const start=e=>{down=true;const q=pos(e);ctx.beginPath();ctx.moveTo(q.x,q.y);e.preventDefault()};const move=e=>{if(!down)return;const q=pos(e);ctx.lineTo(q.x,q.y);ctx.stroke();e.preventDefault()};const end=()=>down=false;['mousedown','touchstart'].forEach(x=>c.addEventListener(x,start,{passive:false}));['mousemove','touchmove'].forEach(x=>c.addEventListener(x,move,{passive:false}));['mouseup','mouseleave','touchend'].forEach(x=>c.addEventListener(x,end));document.getElementById('clearSig').onclick=()=>ctx.clearRect(0,0,c.width,c.height);document.getElementById('signBtn').onclick=()=>{if(!document.getElementById('acceptAgreement').checked)return alert('Debes aceptar las condiciones antes de firmar.');sessionStorage.setItem('esgSignedAt',new Date().toISOString());R.navigate('post-sign',{...params})}}
function renderPostSign(params){app.innerHTML=`<section class="stone-card form-card"><span class="eyebrow">Acuerdo aceptado</span><h1>¿Quieres completar la entrevista ahora?</h1><p>Puedes hacerla ahora o continuar después. El acuerdo no depende de haber hecho primero la entrevista.</p><div class="btn-row">${btn('Completar entrevista ahora',`data-route="interview-intro" data-family="${params.family}" data-service="${params.service}" data-flow="post-sign"`,'btn-dark')}<a class="btn btn-secondary" target="_blank" rel="noopener" href="https://wa.me/17863032835?text=${encodeURIComponent('Firmé mi acuerdo ESG y completaré la entrevista después.')} ">Completar después</a></div></section>`}
function renderInterviewIntro(params){const p=D.packages[params.service];setDocTitle('Mini entrevista');app.innerHTML=`<section class="stone-card form-card"><span class="eyebrow">Antes de las preguntas</span><h1>Aquí sí vamos a entender tu problema antes de producir.</h1><p>Esta entrevista no existe para hacerte llenar campos por llenar. Tus respuestas nos permiten construir el Kit Visual, Brief, dirección y, según el servicio, personaje, contenido o web.</p><div class="note"><strong>${D.brand.transversal.name}</strong><br>${D.brand.transversal.text}</div><div class="btn-row">${btn('Comenzar entrevista',`data-route="interview" data-family="${params.family}" data-service="${params.service}" data-flow="${params.flow||'interview'}"`,'btn-dark')}</div></section>`}
function renderInterview(params){const family=params.family,questions=[...D.interview.general,...(D.interview[family]||[])];setDocTitle('Entrevista');app.innerHTML=`<section class="stone-card form-card"><span class="eyebrow">Mini entrevista de marca</span><h1>${esc(D.packages[params.service].title)}</h1><form id="interviewForm" class="form-grid">${questions.map((q,i)=>`<div class="field full"><label>${i+1}. ${esc(q)}</label><textarea name="q${i+1}" ${i<10?'required':''}></textarea></div>`).join('')}<div class="field full">${btn('Revisar resumen','type="submit"','btn-dark')}</div></form></section>`;document.getElementById('interviewForm').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));sessionStorage.setItem('esgInterview',JSON.stringify({questions,data}));R.navigate('interview-summary',params)}}
function renderInterviewSummary(params){const saved=JSON.parse(sessionStorage.getItem('esgInterview')||'{"questions":[],"data":{}}');setDocTitle('Resumen entrevista');app.innerHTML=`<section class="stone-card form-card"><span class="eyebrow">Resumen</span><h1>Revisa lo que nos estás enviando.</h1><div class="detail-stack">${saved.questions.map((q,i)=>`<article class="detail-item"><h3>${esc(q)}</h3><p>${esc(saved.data['q'+(i+1)]||'—')}</p></article>`).join('')}</div><div class="btn-row">${params.flow==='post-sign'?`<a class="btn btn-dark" target="_blank" rel="noopener" href="https://wa.me/17863032835?text=${encodeURIComponent('Completé mi entrevista ESG.')} ">Enviar confirmación por WhatsApp</a>`:btn('Continuar al contrato',`data-route="client-data" data-family="${params.family}" data-service="${params.service}" data-flow="contract"`,'btn-dark')}</div></section>`}
function render404(){setDocTitle('No encontrado');app.innerHTML=`<section class="stone-card"><h1>Pantalla no encontrada</h1>${btn('Volver al inicio','data-route="home"','btn-dark')}</section>`}
function render(route,params={}){menu.hidden=true;back.style.visibility=route==='home'?'hidden':'visible';switch(route){case'home':renderHome();break;case'family':renderFamily(params.family);break;case'service':renderService(params.service);break;case'request-picker':renderRequestPicker();break;case'purchase-mode':renderPurchaseMode(params);break;case'client-data':renderClientData(params);break;case'agreement':renderAgreement(params);break;case'post-sign':renderPostSign(params);break;case'interview-intro':renderInterviewIntro(params);break;case'interview':renderInterview(params);break;case'interview-summary':renderInterviewSummary(params);break;default:render404()}scrollTop()}
app.addEventListener('click',e=>{const el=e.target.closest('[data-route]');if(!el)return;const route=el.dataset.route,params={...el.dataset};delete params.route;if(route==='family')R.resetFamily();R.navigate(route,params)});document.body.addEventListener('click',e=>{const el=e.target.closest('button[data-route],a[data-route]');if(!el||app.contains(el))return;e.preventDefault();const params={...el.dataset},route=params.route;delete params.route;R.navigate(route,params)});back.onclick=()=>R.goBack();menuBtn.onclick=()=>menu.hidden=!menu.hidden;menu.addEventListener('click',e=>{const el=e.target.closest('[data-route]');if(!el)return;const params={...el.dataset},route=params.route;delete params.route;R.navigate(route,params)});window.addEventListener('esg:navigate',e=>render(e.detail.route,e.detail.params));const initial=history.state||{route:'home',params:{}};history.replaceState(initial,'',location.pathname+'#'+initial.route);R.state.route=initial.route;R.state.params=initial.params||{};render(initial.route,initial.params);
})();
